-- PostgreSQL schema: obras, compositores, directores, intérpretes e interpretaciones

BEGIN;

-- ---------------------------------------------------------------------------
-- Tablas base
-- ---------------------------------------------------------------------------

CREATE TABLE user_app (
    id_user   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name      VARCHAR(255) NOT NULL,
    email     VARCHAR(255) NOT NULL,
    CONSTRAINT uq_user_app_email UNIQUE (email)
);

CREATE TABLE composer (
    id_composer INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_user     INTEGER REFERENCES user_app (id_user) ON DELETE SET NULL ON UPDATE CASCADE,
    nickname    VARCHAR(255) NOT NULL,
    description TEXT NOT NULL DEFAULT ''
);

CREATE TABLE work (
    id_work     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255) NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    write_date  DATE NOT NULL
);

CREATE TABLE composition (
    id_composition INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_composer    INTEGER NOT NULL REFERENCES composer (id_composer) ON DELETE RESTRICT ON UPDATE CASCADE,
    id_work        INTEGER NOT NULL REFERENCES work (id_work) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT uq_composition_work_composer UNIQUE (id_work, id_composer)
);

CREATE TABLE genre (
    id_genre    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255) NOT NULL,
    description TEXT NOT NULL DEFAULT ''
);

CREATE TABLE work_genre (
    id_work_genre INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_work       INTEGER NOT NULL REFERENCES work (id_work) ON DELETE CASCADE ON UPDATE CASCADE,
    id_genre      INTEGER NOT NULL REFERENCES genre (id_genre) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT uq_work_genre_work_genre UNIQUE (id_work, id_genre)
);

CREATE TABLE director (
    id_director INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_user     INTEGER REFERENCES user_app (id_user) ON DELETE SET NULL ON UPDATE CASCADE,
    nickname    VARCHAR(255) NOT NULL,
    description TEXT NOT NULL DEFAULT ''
);

CREATE TABLE artist (
    id_artist   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_user     INTEGER REFERENCES user_app (id_user) ON DELETE SET NULL ON UPDATE CASCADE,
    nickname    VARCHAR(255) NOT NULL,
    description TEXT NOT NULL DEFAULT ''
);

CREATE TABLE type_instrument (
    id_type_instrument INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name               VARCHAR(255) NOT NULL,
    description        TEXT NOT NULL DEFAULT ''
);

CREATE TABLE instrument (
    id_instrument      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_type_instrument INTEGER NOT NULL REFERENCES type_instrument (id_type_instrument) ON DELETE RESTRICT ON UPDATE CASCADE,
    name               VARCHAR(255) NOT NULL,
    description        TEXT NOT NULL DEFAULT ''
);

CREATE TABLE type_interpretation (
    id_type_interpretation INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                   VARCHAR(255) NOT NULL,
    description            TEXT NOT NULL DEFAULT '',
    min_artist             INTEGER NOT NULL,
    max_artist             INTEGER NOT NULL,
    CONSTRAINT chk_type_interpretation_artist_range CHECK (min_artist >= 0 AND max_artist >= min_artist)
);

CREATE TABLE interpretation (
    id_interpretation      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_type_interpretation INTEGER REFERENCES type_interpretation (id_type_interpretation) ON DELETE RESTRICT ON UPDATE CASCADE,
    id_work                INTEGER NOT NULL REFERENCES work (id_work) ON DELETE CASCADE ON UPDATE CASCADE,
    id_director            INTEGER REFERENCES director (id_director) ON DELETE RESTRICT ON UPDATE CASCADE,
    load_file_date         DATE NOT NULL DEFAULT CURRENT_DATE
);

CREATE TABLE interpretation_artist (
    id_interpretation_artist INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_artist                INTEGER NOT NULL REFERENCES artist (id_artist) ON DELETE RESTRICT ON UPDATE CASCADE,
    id_instrument            INTEGER REFERENCES instrument (id_instrument) ON DELETE RESTRICT ON UPDATE CASCADE,
    id_interpretation        INTEGER NOT NULL REFERENCES interpretation (id_interpretation) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT uq_interpretation_artist_interpretation_artist UNIQUE (id_interpretation, id_artist)
);

-- ---------------------------------------------------------------------------
-- Índices (consultas por artista, director y obra)
-- ---------------------------------------------------------------------------

CREATE INDEX idx_composition_id_composer ON composition (id_composer);
CREATE INDEX idx_composition_id_work ON composition (id_work);

CREATE INDEX idx_work_genre_id_genre ON work_genre (id_genre);

CREATE INDEX idx_interpretation_id_work ON interpretation (id_work);
CREATE INDEX idx_interpretation_id_director ON interpretation (id_director);
CREATE INDEX idx_interpretation_id_type_interpretation ON interpretation (id_type_interpretation);

CREATE INDEX idx_interpretation_artist_id_artist ON interpretation_artist (id_artist);
CREATE INDEX idx_interpretation_artist_id_interpretation ON interpretation_artist (id_interpretation);
CREATE INDEX idx_interpretation_artist_id_instrument ON interpretation_artist (id_instrument);

CREATE INDEX idx_composer_id_user ON composer (id_user);
CREATE INDEX idx_director_id_user ON director (id_user);
CREATE INDEX idx_artist_id_user ON artist (id_user);

COMMIT;
